<?php
require_once __DIR__.'/includes/db.php';require_once __DIR__.'/includes/auth.php';
$me=auth_require_role('superadmin');
?><!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Super-Admin – Schul-Dashboard</title><link rel="stylesheet" href="assets/css/styles.css"></head><body>
<header class="topbar"><div class="topbar-inner"><h1><span class="logo">🛡️</span> Super-Admin</h1><nav><a href="index.php" class="btn btn-ghost">← Dashboard</a><span class="topbar-user">👤 <?=htmlspecialchars($me['username'])?></span><a href="logout.php" class="btn btn-ghost">Abmelden</a></nav></div></header>
<main class="settings-page" style="max-width:1000px;">
<div class="admin-tabs"><button class="admin-tab active" data-tab="tenants">🏢 Mandanten</button><button class="admin-tab" data-tab="users">👥 Benutzer</button></div>
<section id="tab-tenants" class="settings-form admin-tab-panel"><div style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:8px;"><h2 style="border:none;padding:0;margin:0;">Mandanten</h2><button class="btn btn-primary" id="btn-new-tenant">+ Neuer Mandant</button></div><div id="tenant-list"><p class="hint">Wird geladen…</p></div></section>
<section id="tab-users" class="settings-form admin-tab-panel" hidden><div style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:8px;"><h2 style="border:none;padding:0;margin:0;">Benutzer</h2><div style="display:flex;gap:8px;align-items:center;"><select id="user-tenant-filter" class="filter-select" style="min-width:180px;"><option value="">Alle Mandanten</option></select><button class="btn btn-primary" id="btn-new-user">+ Neuer Benutzer</button></div></div><div id="user-list"><p class="hint">Wird geladen…</p></div></section>
</main>
<dialog id="dlg-tenant"><div class="modal-form"><h3 id="dlg-tenant-title">Neuer Mandant</h3><input type="hidden" id="t-id"><label style="display:flex;flex-direction:column;gap:4px;font-size:13px;color:var(--text-muted);font-weight:600;">Name<input type="text" id="t-name" maxlength="100" placeholder="z.B. Familie Müller" style="font:inherit;padding:8px 10px;border:1px solid var(--border);border-radius:var(--radius-sm);"></label><label style="display:flex;align-items:center;gap:8px;font-size:13px;font-weight:600;cursor:pointer;"><input type="checkbox" id="t-active" checked style="width:16px;height:16px;cursor:pointer;"> Aktiv</label><div id="t-error" class="alert alert-danger" hidden></div><menu class="modal-actions"><button type="button" class="btn btn-danger" id="t-btn-del" hidden>Löschen</button><span class="spacer"></span><button type="button" class="btn btn-ghost" id="t-btn-cancel">Abbrechen</button><button type="button" class="btn btn-primary" id="t-btn-save">Speichern</button></menu></div></dialog>
<dialog id="dlg-user"><div class="modal-form"><h3 id="dlg-user-title">Neuer Benutzer</h3><input type="hidden" id="u-id"><label style="display:flex;flex-direction:column;gap:4px;font-size:13px;color:var(--text-muted);font-weight:600;">Mandant<select id="u-tenant" style="font:inherit;padding:8px 10px;border:1px solid var(--border);border-radius:var(--radius-sm);"></select></label><label style="display:flex;flex-direction:column;gap:4px;font-size:13px;color:var(--text-muted);font-weight:600;">Benutzername<input type="text" id="u-username" maxlength="100" style="font:inherit;padding:8px 10px;border:1px solid var(--border);border-radius:var(--radius-sm);"></label><label style="display:flex;flex-direction:column;gap:4px;font-size:13px;color:var(--text-muted);font-weight:600;">Passwort <small id="u-pw-hint">(Pflichtfeld)</small><input type="password" id="u-password" style="font:inherit;padding:8px 10px;border:1px solid var(--border);border-radius:var(--radius-sm);"></label><label style="display:flex;flex-direction:column;gap:4px;font-size:13px;color:var(--text-muted);font-weight:600;">Rolle<select id="u-role" style="font:inherit;padding:8px 10px;border:1px solid var(--border);border-radius:var(--radius-sm);"><option value="user">👤 Nutzer</option><option value="tenant_admin">🔑 Admin</option></select></label><label style="display:flex;align-items:center;gap:8px;font-size:13px;font-weight:600;cursor:pointer;"><input type="checkbox" id="u-active" checked style="width:16px;height:16px;cursor:pointer;"> Aktiv</label><div id="u-error" class="alert alert-danger" hidden></div><menu class="modal-actions"><button type="button" class="btn btn-danger" id="u-btn-del" hidden>Löschen</button><span class="spacer"></span><button type="button" class="btn btn-ghost" id="u-btn-cancel">Abbrechen</button><button type="button" class="btn btn-primary" id="u-btn-save">Speichern</button></menu></div></dialog>
<script>
const API='api/admin.php';let _t=[],_u=[];
function esc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
async function af(url,m='GET',b=null){const o={method:m,headers:{}};if(b){o.headers['Content-Type']='application/json';o.body=JSON.stringify(b);}const r=await fetch(url,o);const j=await r.json();if(!r.ok)throw new Error(j.error||'Fehler '+r.status);return j;}
document.querySelectorAll('.admin-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.admin-tab').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.admin-tab-panel').forEach(p=>p.hidden=true);btn.classList.add('active');document.getElementById('tab-'+btn.dataset.tab).hidden=false;if(btn.dataset.tab==='tenants')loadT();else loadU();}));
async function loadT(){const w=document.getElementById('tenant-list');w.innerHTML='<p class="hint">Laden…</p>';_t=await af(`${API}?resource=tenants`);const s=document.getElementById('user-tenant-filter');s.innerHTML='<option value="">Alle</option>';const ut=document.getElementById('u-tenant');ut.innerHTML='';for(const t of _t){s.innerHTML+=`<option value="${t.id}">${esc(t.name)}</option>`;ut.innerHTML+=`<option value="${t.id}">${esc(t.name)}</option>`;}if(!_t.length){w.innerHTML='<p class="hint">Noch keine Mandanten.</p>';return;}let h='<table style="width:100%;border-collapse:collapse;font-size:13px;margin-top:8px;"><thead><tr style="border-bottom:2px solid var(--border)"><th style="text-align:left;padding:7px 8px">Name</th><th style="text-align:left;padding:7px 8px">Status</th><th style="text-align:left;padding:7px 8px">User</th><th></th></tr></thead><tbody>';for(const t of _t)h+=`<tr style="border-bottom:1px solid var(--border)"><td style="padding:7px 8px;font-weight:600">${esc(t.name)}</td><td style="padding:7px 8px">${t.active?'✅':'❌'}</td><td style="padding:7px 8px">${t.user_count??0}</td><td style="padding:7px 8px;text-align:right"><button class="btn btn-ghost" style="padding:3px 10px;font-size:12px" onclick="editT(${t.id})">Bearbeiten</button></td></tr>`;w.innerHTML=h+'</tbody></table>';}
window.editT=id=>{const t=_t.find(x=>x.id==id);if(t)openT(t);};
const dlgT=document.getElementById('dlg-tenant'),tTitle=document.getElementById('dlg-tenant-title'),tId=document.getElementById('t-id'),tName=document.getElementById('t-name'),tActive=document.getElementById('t-active'),tErr=document.getElementById('t-error'),tBtnDel=document.getElementById('t-btn-del');
function openT(t=null){tErr.hidden=true;tId.value=t?t.id:'';tName.value=t?t.name:'';tActive.checked=t?!!t.active:true;tTitle.textContent=t?'Bearbeiten':'Neuer Mandant';tBtnDel.hidden=!t;dlgT.showModal();}
document.getElementById('btn-new-tenant').addEventListener('click',()=>openT());
document.getElementById('t-btn-cancel').addEventListener('click',()=>dlgT.close());
document.getElementById('t-btn-save').addEventListener('click',async()=>{tErr.hidden=true;const id=tId.value?parseInt(tId.value):null,name=tName.value.trim(),active=tActive.checked?1:0;if(!name){tErr.textContent='Name ist Pflicht.';tErr.hidden=false;return;}try{const b={name,active};if(id)b.id=id;await af(`${API}?resource=tenants`,id?'PUT':'POST',b);dlgT.close();loadT();}catch(e){tErr.textContent=e.message;tErr.hidden=false;}});
document.getElementById('t-btn-del').addEventListener('click',async()=>{const id=parseInt(tId.value),name=tName.value;if(!id||!confirm(`Mandant „${name}" und ALLE Daten unwiderruflich löschen?`))return;try{await af(`${API}?resource=tenants&id=${id}`,'DELETE');dlgT.close();loadT();}catch(e){tErr.textContent=e.message;tErr.hidden=false;}});
async function loadU(tid=null){const w=document.getElementById('user-list');w.innerHTML='<p class="hint">Laden…</p>';const url=tid?`${API}?resource=users&tenant_id=${tid}`:`${API}?resource=users`;_u=await af(url);if(!_u.length){w.innerHTML='<p class="hint">Keine Benutzer.</p>';return;}let h='<table style="width:100%;border-collapse:collapse;font-size:13px;margin-top:8px;"><thead><tr style="border-bottom:2px solid var(--border)"><th style="text-align:left;padding:7px 8px">Mandant</th><th style="text-align:left;padding:7px 8px">Benutzer</th><th style="text-align:left;padding:7px 8px">Rolle</th><th style="text-align:left;padding:7px 8px">Status</th><th style="text-align:left;padding:7px 8px">Login</th><th></th></tr></thead><tbody>';for(const u of _u)h+=`<tr style="border-bottom:1px solid var(--border)"><td style="padding:7px 8px;color:var(--text-muted)">${esc(u.tenant_name||'–')}</td><td style="padding:7px 8px;font-weight:600">${esc(u.username)}</td><td style="padding:7px 8px">${u.role==='tenant_admin'?'🔑 Admin':'👤 Nutzer'}</td><td style="padding:7px 8px">${u.active?'✅':'❌'}</td><td style="padding:7px 8px;color:var(--text-muted)">${esc((u.last_login||'–').slice(0,16))}</td><td style="padding:7px 8px;text-align:right"><button class="btn btn-ghost" style="padding:3px 10px;font-size:12px" onclick="editU(${u.id})">Bearbeiten</button></td></tr>`;w.innerHTML=h+'</tbody></table>';}
document.getElementById('user-tenant-filter').addEventListener('change',function(){loadU(this.value||null);});
window.editU=id=>{const u=_u.find(x=>x.id==id);if(u)openU(u);};
const dlgU=document.getElementById('dlg-user'),uTitle=document.getElementById('dlg-user-title'),uId=document.getElementById('u-id'),uTenant=document.getElementById('u-tenant'),uUname=document.getElementById('u-username'),uPw=document.getElementById('u-password'),uPwHint=document.getElementById('u-pw-hint'),uRole=document.getElementById('u-role'),uActive=document.getElementById('u-active'),uErr=document.getElementById('u-error'),uBtnDel=document.getElementById('u-btn-del');
function openU(u=null){uErr.hidden=true;uId.value=u?u.id:'';uUname.value=u?u.username:'';uPw.value='';uRole.value=u?u.role:'user';uActive.checked=u?!!u.active:true;if(u&&u.tenant_id)uTenant.value=u.tenant_id;uTitle.textContent=u?'Bearbeiten':'Neuer Benutzer';uPwHint.textContent=u?'(leer=unverändert)':'(Pflichtfeld)';uBtnDel.hidden=!u;dlgU.showModal();}
document.getElementById('btn-new-user').addEventListener('click',()=>openU());
document.getElementById('u-btn-cancel').addEventListener('click',()=>dlgU.close());
document.getElementById('u-btn-save').addEventListener('click',async()=>{uErr.hidden=true;const id=uId.value?parseInt(uId.value):null,tid=parseInt(uTenant.value),uname=uUname.value.trim(),pw=uPw.value,role=uRole.value,active=uActive.checked?1:0;if(!uname){uErr.textContent='Benutzername ist Pflicht.';uErr.hidden=false;return;}if(!id&&!pw){uErr.textContent='Passwort ist Pflicht.';uErr.hidden=false;return;}if(!id&&!tid){uErr.textContent='Mandant ist Pflicht.';uErr.hidden=false;return;}try{const b={username:uname,role,active};if(pw)b.password=pw;if(id)b.id=id;else b.tenant_id=tid;await af(`${API}?resource=users`,id?'PUT':'POST',b);dlgU.close();loadU(document.getElementById('user-tenant-filter').value||null);}catch(e){uErr.textContent=e.message;uErr.hidden=false;}});
document.getElementById('u-btn-del').addEventListener('click',async()=>{const id=parseInt(uId.value),uname=uUname.value;if(!id||!confirm(`Benutzer „${uname}" unwiderruflich löschen?`))return;try{await af(`${API}?resource=users&id=${id}`,'DELETE');dlgU.close();loadU(document.getElementById('user-tenant-filter').value||null);}catch(e){uErr.textContent=e.message;uErr.hidden=false;}});
loadT();
</script>
</body></html>
