<?php
require_once __DIR__.'/../includes/db.php';
require_once __DIR__.'/../includes/auth.php';
auth_require_role('superadmin');
$method=$_SERVER['REQUEST_METHOD'];$resource=$_GET['resource']??'';
try {
    if ($resource==='tenants'){
        if ($method==='GET'){json_response(db()->query("SELECT t.id,t.name,t.active,t.created_at,(SELECT COUNT(*) FROM users u WHERE u.tenant_id=t.id) AS user_count FROM tenants t ORDER BY t.name ASC")->fetchAll());}
        if ($method==='POST'){$d=read_json_body();$name=trim((string)($d['name']??''));if ($name==='') json_response(['error'=>'Name ist Pflicht.'],400);$chk=db()->prepare("SELECT id FROM tenants WHERE name=?");$chk->execute([$name]);if ($chk->fetch()) json_response(['error'=>'Name bereits vergeben.'],409);db()->prepare("INSERT INTO tenants (name,active) VALUES (?,1)")->execute([$name]);$tid=(int)db()->lastInsertId();ensure_tenant_settings($tid);json_response(['id'=>$tid],201);}
        if ($method==='PUT'||$method==='PATCH'){$d=read_json_body();$id=(int)($d['id']??0);if ($id<=0) json_response(['error'=>'id fehlt'],400);$fields=[];$params=[];if(isset($d['name'])){$n=trim((string)$d['name']);if($n==='')json_response(['error'=>'Name darf nicht leer sein.'],400);$chk=db()->prepare("SELECT id FROM tenants WHERE name=? AND id!=?");$chk->execute([$n,$id]);if($chk->fetch())json_response(['error'=>'Name bereits vergeben.'],409);$fields[]='name=?';$params[]=$n;}if(isset($d['active'])){$fields[]='active=?';$params[]=(int)(bool)$d['active'];}if(!$fields)json_response(['error'=>'Keine Felder.'],400);$params[]=$id;db()->prepare("UPDATE tenants SET ".implode(',',$fields)." WHERE id=?")->execute($params);json_response(['ok'=>true]);}
        if ($method==='DELETE'){$id=(int)($_GET['id']??0);if($id<=0)json_response(['error'=>'id fehlt'],400);db()->prepare("DELETE FROM tenants WHERE id=?")->execute([$id]);json_response(['ok'=>true]);}
    }
    if ($resource==='users'){
        if ($method==='GET'){$tid=isset($_GET['tenant_id'])?(int)$_GET['tenant_id']:null;if($tid){$s=db()->prepare("SELECT u.id,u.tenant_id,t.name AS tenant_name,u.username,u.role,u.active,u.last_login,u.created_at FROM users u LEFT JOIN tenants t ON t.id=u.tenant_id WHERE u.tenant_id=? ORDER BY u.username ASC");$s->execute([$tid]);}else{$s=db()->query("SELECT u.id,u.tenant_id,t.name AS tenant_name,u.username,u.role,u.active,u.last_login,u.created_at FROM users u LEFT JOIN tenants t ON t.id=u.tenant_id ORDER BY t.name ASC,u.username ASC");}json_response($s->fetchAll());}
        if ($method==='POST'){$d=read_json_body();$tid=(int)($d['tenant_id']??0);$username=trim((string)($d['username']??''));$password=(string)($d['password']??'');$role=(string)($d['role']??'user');if($tid<=0)json_response(['error'=>'tenant_id ist Pflicht.'],400);if($username==='')json_response(['error'=>'Benutzername ist Pflicht.'],400);if($password==='')json_response(['error'=>'Passwort ist Pflicht.'],400);if(strlen($password)<6)json_response(['error'=>'Passwort mind. 6 Zeichen.'],400);if(!in_array($role,['user','tenant_admin'],true))$role='user';$chk=db()->prepare("SELECT id FROM users WHERE username=?");$chk->execute([$username]);if($chk->fetch())json_response(['error'=>'Benutzername bereits vergeben.'],409);db()->prepare("INSERT INTO users (tenant_id,username,password_hash,role) VALUES (?,?,?,?)")->execute([$tid,$username,password_hash($password,PASSWORD_BCRYPT),$role]);json_response(['id'=>(int)db()->lastInsertId()],201);}
        if ($method==='PUT'||$method==='PATCH'){$d=read_json_body();$id=(int)($d['id']??0);if($id<=0)json_response(['error'=>'id fehlt'],400);$fields=[];$params=[];if(isset($d['username'])){$u=trim((string)$d['username']);if($u==='')json_response(['error'=>'Benutzername darf nicht leer sein.'],400);$chk=db()->prepare("SELECT id FROM users WHERE username=? AND id!=?");$chk->execute([$u,$id]);if($chk->fetch())json_response(['error'=>'Benutzername bereits vergeben.'],409);$fields[]='username=?';$params[]=$u;}if(isset($d['password'])&&$d['password']!==''){if(strlen($d['password'])<6)json_response(['error'=>'Passwort mind. 6 Zeichen.'],400);$fields[]='password_hash=?';$params[]=password_hash($d['password'],PASSWORD_BCRYPT);}if(isset($d['role'])){if(!in_array($d['role'],['user','tenant_admin'],true))json_response(['error'=>'Ungültige Rolle.'],400);$fields[]='role=?';$params[]=$d['role'];}if(isset($d['active'])){$fields[]='active=?';$params[]=(int)(bool)$d['active'];}if(isset($d['tenant_id'])){$fields[]='tenant_id=?';$params[]=(int)$d['tenant_id'];}if(!$fields)json_response(['error'=>'Keine Felder.'],400);$params[]=$id;db()->prepare("UPDATE users SET ".implode(',',$fields)." WHERE id=?")->execute($params);json_response(['ok'=>true]);}
        if ($method==='DELETE'){$id=(int)($_GET['id']??0);if($id<=0)json_response(['error'=>'id fehlt'],400);db()->prepare("DELETE FROM users WHERE id=?")->execute([$id]);json_response(['ok'=>true]);}
    }
    json_response(['error'=>'Unbekannte Resource.'],400);
} catch (Throwable $e){json_response(['error'=>'Serverfehler','detail'=>$e->getMessage()],500);}
